name: Deploy hw1 to GitHub Pages

on:
  push:
    branches:
      - master # Or whatever your main branch is
    paths:
      - 'hw1/**' # Trigger only when changes occur in hw1 folder
      - '.github/workflows/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is crucial for the bot to push to gh-pages
      pages: write # Recommended for GitHub Pages deployments
      id-token: write # Required for OIDC, good practice for modern deployments


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or your preferred Node.js version

      - name: Install dependencies for hw1
        run: |
          cd hw1
          npm install

      - name: Build hw1
        run: |
          cd hw1
          npm run build

      - name: Build hw1
        run: |
          cd hw1
          npm run build # This step should now consistently succeed!

      - name: Deploy hw1 to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hw1/build
          publish_branch: gh-pages
          # cname: YOUR_USERNAME.github.io # If you have a custom domain for the main repo
          # This is how you target a subfolder:
          # By default, peaceiris/actions-gh-pages publishes to the root of gh-pages.
          # To publish to a subfolder, you need to copy the build output
          # into a structure that mirrors your desired URL.
          # A common approach is to build all projects into a 'deploy' folder
          # at the root, maintaining the subfolder structure.

      # Example for a multi-project deployment with a custom deploy folder:
      # This approach makes a 'deploy' folder at the root of your repo
      # and copies each project's build output into its respective subfolder
      # within 'deploy'. Then, 'deploy' is published to gh-pages.

      # - name: Create deployment directory
      #   run: mkdir -p deploy/hw1

      # - name: Copy hw1 build to deployment directory
      #   run: cp -r hw1/build/* deploy/hw1/

      # - name: Deploy 'deploy' folder to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./deploy
      #     cname: YOUR_USERNAME.github.io # If you have a custom domain for the main repo
