# .github/workflows/deploy.yml
name: Deploy React App for hw1 Folder to GitHub Pages
on:
  push:
    branches: [master]
    paths:
      - 'hw1/**'
  pull_request:
    branches: [master]
    paths:
      - 'hw1/**'
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hw1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: hw1/package.json
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          PUBLIC_URL: /react-portfolio # Match homepage path
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: false
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: hw1/build
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4